### ISSUE TITLE
Images are not loading on pub.dev

### ISSUE THREAD

**Issue by nilsreichardt** [Agraphie/blurhash#1]
![image](https://user-images.githubusercontent.com/24459435/154804687-3b357a28-b014-4f23-bb97-7f4888359390.png)

Tested with Chrome on macOS.

On GitHub, they are loading.

**Comment by Agraphie** [comment]
Hi.

Thanks a lot for reporting. Unfortunately, I missed this issue. I updated the readme and the images appear on pub.dev now as well! https://pub.dev/packages/blurhash_flutter
